POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = custom
SRC += iqs5xx.c i2c_master.c qmk_rc.c
ENCODER_MAP_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = vendor
HAPTIC_ENABLE = yes
HAPTIC_DRIVER += DRV2605L