// Copyright 2023 Daraku-Neko (@Daraku-Neko)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define VIAL_KEYBOARD_UID {0x01, 0x60, 0x0F, 0x55, 0x54, 0xD2, 0xCD, 0x35}

/* CONSIDER ADDING AN UNLOCK COMBO. SEE DOCUMENTATION. */
/* CONSIDER ADDING AN UNLOCK COMBO. SEE DOCUMENTATION. */
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}

#define RGBLIGHT_TIMEOUT 1