// Copyright 2023 Daraku-Neko (@Daraku-Neko)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
#define POINTING_DEVICE_HIRES_SCROLL_MULTIPLIER 50
#define POINTING_DEVICE_HIRES_SCROLL_WHEEL_ENABLE
#define POINTING_DEVICE_HIRES_SCROLL_EXPONENT 0

#define WHEEL_EXTENDED_REPORT