name: Sync Firmware Files

on:
  push:
    branches:
      - main
      
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout Source Repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          path: keyboard

      # Checkout Destination Repository (qmk_firmware)
      - name: Checkout Destination Repository (qmk_firmware)
        uses: actions/checkout@v3
        with:
          repository: darakuneko/qmk_firmware
          path: qmk_firmware
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Create or Switch to Sync Branch (qmk_firmware)
        run: |
          cd qmk_firmware
          git checkout -B feature/keyboard-firmware
          git push origin feature/keyboard-firmware || echo "Branch already exists"

      - name: Copy Files to qmk_firmware
        run: |
          rm -rf qmk_firmware/users/*
          find keyboard/qmk -type f ! -name '*.zip' -exec cp --parents {} qmk_firmware/users/ \;

      - name: Commit and Push Changes to qmk_firmware
        run: |
          cd qmk_firmware
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Sync files from keyboard/qmk" || echo "No changes to commit"
          git pull --rebase origin feature/keyboard-firmware
          git push origin feature/keyboard-firmware

      - name: Resolve Merge Conflicts in qmk_firmware (Prefer Remote Changes)
        run: |
          cd qmk_firmware
          git diff --name-only --diff-filter=U | while read -r file; do
          echo "Resolving conflict for $file"
          git checkout --theirs "$file" || true
          git add "$file" || true
          done
          git commit -m "Resolve binary file conflicts by preferring remote changes" || true

      # Checkout Destination Repository (vial-qmk)
      - name: Checkout Destination Repository (vial-qmk)
        uses: actions/checkout@v3
        with:
          repository: darakuneko/vial-qmk
          path: vial-qmk
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Create or Switch to Sync Branch (vial-qmk)
        run: |
          cd vial-qmk
          git checkout -B feature/keyboard-firmware
          git push origin feature/keyboard-firmware || echo "Branch already exists"

      - name: Copy Files to vial-qmk
        run: |
          rm -rf qmk_firmware/users/*
          find keyboard/qmk -type f ! -name '*.zip' -exec cp --parents {} qmk_firmware/users/ \;

      - name: Commit and Push Changes to vial-qmk
        run: |
          cd vial-qmk
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Sync files from keyboard/qmk" || echo "No changes to commit"
          git pull --rebase origin feature/keyboard-firmware
          git push origin feature/keyboard-firmware

      - name: Resolve Merge Conflicts in vial-qmk (Prefer Remote Changes)
        run: |
          cd vial-qmk
          git diff --name-only --diff-filter=U | while read -r file; do
          echo "Resolving conflict for $file"
          git checkout --theirs "$file" || true
          git add "$file" || true
          done
          git commit -m "Resolve binary file conflicts by preferring remote changes" || true
