RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = vendor  
ENCODER_MAP_ENABLE = yes
QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS = st7789_spi
QUANTUM_PAINTER_SUPPORTS_256_PALETTE = yes
QUANTUM_PAINTER_NUM_IMAGES = 1
SRC += \
	pm10.qff.c 

