#pragma once

#define RGB_MATRIX_LED_COUNT 92
#define RGB_MATRIX_CENTER { 112, 32 }
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 180
#define RGB_MATRIX_STARTUP_VAL 180
#define RGB_MATRIX_TIMEOUT 120000
#define RGB_DISABLE_WHEN_USB_SUSPENDED true
#define RGB_MATRIX_HUE_STEP 4
#define RGB_MATRIX_SAT_STEP 4
#define RGB_MATRIX_VAL_STEP 4
#define RGB_MATRIX_SPD_STEP 4
#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS

#define VIAL_KEYBOARD_UID {0xCC, 0x44, 0xF1, 0xE8, 0x14, 0xEC, 0x9A, 0xC7}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}